sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "XZd6y7YV7MkQIebrZr4+8+QLemCSVdr0pteRjBlwYf4y0eSN0LBe+436Evfw3XSKtYMn4ffdHhldellEwS5+dbngM5yZSGo9mzfTR8y2FRMmWyJRMS4Kkx+nMEev0ig/w5JQwX6I31MgQcJt5qq/jPmEew90eHhjlM7eo1PMO3B7qnpoDeGPM44/G2oNnAOKSWdqohpT8U0Qg4B8E1HJr0v61UcZ6Ed0yO46SdAzTLRuXEkBEo+qkWCwewTcvKH8sB/8mKDH9fms2pqqFu3CamsOnHm1TBG07YADTd5Pi0MH8p2V2HcnMxmuZnQuFHzVi+3SHcOqr257CJLPqHZMlmeai4fZWodKt87kKI7QF5KXss41Z34XxzAEz+6PEWQUBK+pHIYqRxeUvoI2NGctFB+uo/5U+mRd4X45SIbJ2b0GuBvYf+COsYlzbR35vibrkN+tsuFtkIEFi92agKoWeCJIRxDMyKa6/jkYslaIqgWYPO/pL3Gw3zESKjkETUVpPS+7C/+1TqHxHpXYrTwKDT9tXOxuo1iJ1SG8mjzjklKEIesUocLwkKJXjWdN1x9dI313p4i0XyrXT0zWPB2PTR/Nnu5fHkNGXyT+coyyQruuPzX27ZQo8u5fkPRu2xEHqiEwDzh3vVNDN4yR9pSXYMSXSU26vZqZXx4v727qS8E="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "Y3I23WWrVsMXsfHHcMujf4LZWZT3qa1GMI7ddYLzDsNUD2INMa1W1fU8eXJ2V1uLmt22exQCrh5I7nATlI8S85qL8Liam8QrIFmYJdDTuV9kwmEpZT4t4oqp/TibdhPDGtqDIupj2ft7eOQFU/uYUAnG4FgBClT0zFWokr/rUr8KQEJqL3Fzsi+moyPUFGw250C8GZBOb51fA/+0n33OPUXJi/hVRixsS6TE+jGqzbNbAwsHbbE9E2znEoxcngB3FbzydFIQxdkM7FRtCiuBVWmDy5XuqftxA9wECI1pJn4DjTD4Tvm6cPhngabEy3gUH9Z+JaWWmgyhZT0kn/R5j53WjkJ1R+yvZ1rY/gnztc3buEBgJr1AUci3OrA2YwglJNpA/7nq6eQkztwMZ9Pkwe11PjY9899IA+PMzQ+3/5NdWG13ZkQEYR7/Wb9a3pPo5WJLaIFSjMfawhluU79/y+qz+rZ3QBp0pzscCvZICujR3umHVRzw9rY4fmSYSFXB++RIPa0quVWfEv2pX2fGn7viUbBG5/CWos3SWekBx8aW7wSRaW+Nflf+K+FHmi7L2ZcbWjNJEQdx4AZRkPd0SF0uREW5h5KP9fyN5tXaBPufe4+afj3iruajetYq2nZPoR9ZhBbG0vEFujv2Cx8NLGdVSSdRRWLSnlyVW7feLpQ="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "rKaR7fmJEzteucbZVhyiFgtae4opfMGbdwTX1LD8c8tJRLzEvfn7BDod9Eos7guBz6d75842gi3aGGX3V/yeFtxK8y3F+nEm1YXv45TnAgHznuamsQvzjiRyAMRp8bHqj3H/L9E2gu8Ix9FMDxiW86HJ3gGdRr1THmTNipdX2LOYyb64Xen4pIkzsE4XtseCG1xPtlNYp/uFe+IkjBgXiDHKoUR4vNlnck9rL3/MdnTo0Xw571wyesuU1b/REvbCPE//eTFDKDDJmc0Yq9y6u4IovrP0cti58tHUSu+tXseGyKsclcrgLxwdjZxoYxJJuCtioEnkjjqbunPz1XKUan8qdhCj0BNPNFY88KnH3wBkajL9xoAQ0XyKgRgk4jxGX5Co1yntjo5W6m/HLKtyC6Z3cHU2rfwqzC7/elT1sGPwHRSyGMPmPNUnuXGAFBVSA4voK8169gAUjkbV30v/y8L77R2mSLUS0svLYNXMWVpOzSy14iaOwVkRAfp/G35QFjyPBsmZhbwztAW1pyD+KPpbWQaT3qfosnKy0K/vhOiLm1v9X0mgFpHzZR3d+G5vV7CfQhtZRqjk7U5Fb6wdpSPjuZCxmtkwgLLqVgQRyxapxKilRhKOFPEJfURyilrXMZwI85x/BKQm7lkO0OJwvG/+YxDVXUSyxO7x1Y/t3MI="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "Xa6pTz7zPkB5qTC9+I4MzbyaTrvyEz6AbKSb6Pv5Z1mUlC2vexY1FqembciUS0jV64kjXrVGTqcN9+9NLoxmPW0WESf8ivpVLcZP0JcFvg4+Qmmq4ngzX5CNovtmELjwxMHyqzUg0jRU8j00jv9CUc5lYnvjgoAECfFTQRw62dn3fnfFuwsRP42zk2AKmhvo8jzXpmsvymhPHN4DxAqGjzN1UYc/TpIhY3h1IZXH2GeV95tSLXuIYyuVMGnUb6E7A6SLWu3GT7bZK//fvZdS9TYe8HMZ6qXHKmmkPsoGNnHWekpjMtVWaKaw8STjUsjoJx8ztzdSn15e5H64eoL91OH98BcqcFyaZSLE4RCRvMpmBeQZ37EEvh2PIQqUockS1GV9E2pY5w97jeK6JPGr07aeyKPsxlVLvuHHD9ejrKOECXlP9afafUZBpersL15uwiCDM/+EPlEkvJZFxICOM4MNtv7OE05GyrXmoBtf6NL9++byZ43wDE0J1Z8ibW8RfnvHqBFhvpN8o4DA48uXLabcbHPTr5CchVzaRVVRgnxsQl0+b2i7QvgY1JYJqHF3qXh9B7rvV+fLiRL8eWD1WsSnYbeA88ZkAEqI7bcV0FhJbZUpsY4qQkyhm4EqsXliQxeeqTdy6UXg2MINQZg5y7jzESH5LHUT37FotEZUGds="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "QD5/9xpA/zt6RkSsPXygxgVTjrgERUo4fyFrr73IBT2kbiZMnAOH0ZpSNV74XUpE0mNp8CNozHenuIri7UfFhx3SCQva4ktack4l42hKck4uqD0PpDQNnfjGC3NzKLfqI7Qmef0L5jPHDCSzTcqzWASVw8F80wTADuYbRP+pptTWRgOOpehpzofwUkhvASW3pXCcPIbj8qYSd1iIWwarUd9rlb/c2zKQTbQQPGd04eeC1Isq8/L8/fG9q2eSDRJBZz1gCbOdB2v+dT9/nRRjyOT5wd6lWCdmQn5zUcs9mgrUIG0pE54eNudMaO/QfPSYRE4WvC2zVRiTtFEYmEznSTlnrnKn1l0Agd+c49MS+ZqPLewzN8mDcZGGgirilOk9Z1fQ8z/z6792w+3ZmbK4BKTkvNluKni6LARPFnAG3KPt1YZ9NldJpGqWJiMUlVyXicvveNTXzxM9pv4jRaumgksjZ7OXTRn00IE9zs+8BX403Oakns4DUS+N9tpjSPEthE3Lx5/f6B5cjOK/aWmB4RwGNzDLeu0i1jLyCgdRbPhpfXxHcfknGKhvHdnXN+oOB/2nGJsV2fYkVc8IQYp9SgyqG9O3if257sNY4zBZoSYASl2Zx1AkI4lqkGLkg2YOdsgqx6iiHFj2v24kIJp6N7HuowV6KKO0+iUfyuM9qag="
